version: '3'

services:
  db:
    image: postgres
    ports: 
            - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: python mysite/manage.py runserver 0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    command: sh -c "cd my-app && npm start"
    ports:
      - "3000:3000"
    networks:
      - external-api
    depends_on:
      - db
    links:
      - db:db

volumes:
  postgres_data:
networks:
  external-api: